/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/bays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bays */
        get: operations["bays_api_bays_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bays/{bay_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bay Detail */
        get: operations["bay_detail_api_bays__bay_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/busbars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busbars */
        get: operations["busbars_api_busbars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Station Diagram
         * @description The whole station in one drawing — every voltage level, stacked.
         */
        get: operations["station_diagram_api_diagram_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagram/{voltage_level}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diagram */
        get: operations["diagram_api_diagram__voltage_level__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/energization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Energization
         * @description Solve which sections are live from the switch positions we can read.
         *
         *     Seeded from the busbars the station measures, spread across closed devices
         *     and through paired transformers, then compared against the bay-level
         *     `IsLive` OneATS publishes. Disagreements are returned, not hidden (I7).
         */
        get: operations["energization_api_energization_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live
         * @description One poll of what `/api/stream` pushes. The fallback when SSE cannot get
         *     through, and what the UI loads before the stream's first event arrives.
         */
        get: operations["live_api_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projects */
        get: operations["projects_api_projects_get"];
        put?: never;
        /**
         * Create Project
         * @description Create a project and immediately try to browse its DataServer.
         *
         *     Success stores a snapshot and makes the project active. Failure keeps the
         *     project so the URL can be corrected and retried with /refresh.
         */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Project
         * @description Remove a project and its snapshot. Returns the remaining projects.
         */
        delete: operations["delete_project_api_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open Project
         * @description Make this project current. Renders from its snapshot when one exists;
         *     only its first-ever open touches the DataServer.
         */
        post: operations["open_project_api_projects__project_id__open_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Project
         * @description Browse the project's DataServer live and replace its snapshot.
         */
        post: operations["refresh_project_api_projects__project_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reload Station
         * @description Re-read the current source: the active project's DataServer (updating
         *     its snapshot), else BI_SOURCE. Writes nothing to OneATS (I1).
         */
        post: operations["reload_station_api_reload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/station": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Station */
        get: operations["station_api_station_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream
         * @description Push the live document whenever anything moves (Server-Sent Events).
         *
         *     The first event is the current state, so a client needs no separate initial
         *     fetch. Read-only in both directions: SSE has no channel back, and the data
         *     behind it is a subscription to OneATS, never a command to it (I1).
         */
        get: operations["stream_api_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BayDetailOut */
        BayDetailOut: {
            /** Bay Type */
            bay_type: string;
            /** Device Count */
            device_count: number;
            /** Devices */
            devices: components["schemas"]["DeviceOut"][];
            /** Id */
            id: string;
            /** Is Live */
            is_live: boolean | null;
            is_live_quality: components["schemas"]["Quality"];
            /** Issues */
            issues: components["schemas"]["ValidationIssue"][];
            /** Logical Nodes */
            logical_nodes: string[];
            /** Name */
            name: string;
            /** Template Id */
            template_id: string | null;
            /** Voltage Level */
            voltage_level: string;
        };
        /** BayOut */
        BayOut: {
            /** Bay Type */
            bay_type: string;
            /** Device Count */
            device_count: number;
            /** Id */
            id: string;
            /** Is Live */
            is_live: boolean | null;
            is_live_quality: components["schemas"]["Quality"];
            /** Issues */
            issues: components["schemas"]["ValidationIssue"][];
            /** Logical Nodes */
            logical_nodes: string[];
            /** Name */
            name: string;
            /** Template Id */
            template_id: string | null;
            /** Voltage Level */
            voltage_level: string;
        };
        /** BusbarOut */
        BusbarOut: {
            /** Id */
            id: string;
            /** Index */
            index: number;
            /** Inferred */
            inferred: boolean;
            /** Is Live */
            is_live: boolean | null;
            /** Name */
            name: string;
            quality: components["schemas"]["Quality"];
            /** Voltage Level */
            voltage_level: string;
        };
        /** ColumnView */
        ColumnView: {
            /** Bay Id */
            bay_id: string;
            /** Bay Type */
            bay_type: string;
            /** Bottom */
            bottom: number;
            /** Caption */
            caption: string;
            /**
             * Error Count
             * @default 0
             */
            error_count: number;
            /**
             * Flipped
             * @default false
             */
            flipped: boolean;
            /**
             * Issue Count
             * @default 0
             */
            issue_count: number;
            /** Label */
            label: string;
            /** Label Y */
            label_y: number;
            /** Template Id */
            template_id: string | null;
            /** Top */
            top: number;
            /** X */
            x: number;
        };
        /**
         * CrossCheck
         * @description Our verdict for a bay against the one OneATS publishes for it.
         *
         *     `agrees is None` means the comparison could not be made — either we say
         *     `UNKNOWN` or OneATS's `IsLive` is not readable. Not comparable is not the
         *     same as agreeing, and is never counted as one.
         */
        CrossCheck: {
            /** Agrees */
            agrees?: boolean | null;
            /** Bay Id */
            bay_id: string;
            computed: components["schemas"]["LiveState"];
            /** Node Id */
            node_id: string;
            /** @default MISSING */
            quality: components["schemas"]["Quality"];
            /** Reported */
            reported?: boolean | null;
        };
        /**
         * DeviceLiveOut
         * @description A switching device's position, and how much to trust it.
         *
         *     `value` is the raw Dbpos behind `state`, carried so a panel showing live
         *     data can still show its provenance — an operator questioning a symbol
         *     should not have to refetch the bay to see what the DataServer actually
         *     said (I6).
         */
        DeviceLiveOut: {
            quality: components["schemas"]["Quality"];
            /** Source Timestamp */
            source_timestamp?: string | null;
            state: components["schemas"]["SwitchState"];
            /** Value */
            value?: number | boolean | string | null;
        };
        /** DeviceOut */
        DeviceOut: {
            /** Id */
            id: string;
            /** Ln */
            ln: string;
            /** Name */
            name: string;
            quality: components["schemas"]["Quality"];
            /** Role */
            role: string;
            /** Short Name */
            short_name: string;
            /** Source Ref */
            source_ref: string | null;
            /** Source Timestamp */
            source_timestamp: string | null;
            state: components["schemas"]["SwitchState"];
            /** Terminals */
            terminals: string[];
            /** Value */
            value: number | boolean | string | null;
        };
        /**
         * DeviceRole
         * @description Electrical role of a switching device inside its bay.
         * @enum {string}
         */
        DeviceRole: "breaker" | "busbar_selector" | "transfer_selector" | "line_disconnector" | "transformer_disconnector" | "earth_switch";
        /** DiagramView */
        DiagramView: {
            /**
             * Columns
             * @default []
             */
            columns: components["schemas"]["ColumnView"][];
            /**
             * Edges
             * @default []
             */
            edges: components["schemas"]["EdgeView"][];
            /** Height */
            height: number;
            /**
             * Junctions
             * @default []
             */
            junctions: components["schemas"]["JunctionView"][];
            /**
             * Rails
             * @default []
             */
            rails: components["schemas"]["RailView"][];
            /**
             * Symbols
             * @default []
             */
            symbols: components["schemas"]["SymbolView"][];
            /**
             * Terminals
             * @default []
             */
            terminals: components["schemas"]["TerminalView"][];
            /** Voltage Level */
            voltage_level: string;
            /** Width */
            width: number;
        };
        /** EdgeView */
        EdgeView: {
            /** Device Id */
            device_id?: string | null;
            /** Id */
            id: string;
            /** Node Id */
            node_id?: string | null;
            /** Points */
            points: components["schemas"]["Point"][];
        };
        /**
         * EnergizationOut
         * @description Which conductors are live, why, and whether OneATS agrees.
         *
         *     `node_state` is keyed by connectivity node so the drawing can be coloured by
         *     joining on `RailView.node_id` / `EdgeView.node_id` — geometry and
         *     energisation stay separate, which is what will let the realtime module push
         *     a new verdict without re-laying-out the station.
         */
        EnergizationOut: {
            /** Checks */
            checks: components["schemas"]["CrossCheck"][];
            /** Islands */
            islands: components["schemas"]["Island"][];
            /** Issues */
            issues: components["schemas"]["ValidationIssue"][];
            /** Node State */
            node_state: {
                [key: string]: components["schemas"]["LiveState"];
            };
            /** Summary */
            summary: {
                [key: string]: number;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Load Error */
            load_error?: string | null;
            /** Load Seconds */
            load_seconds?: number | null;
            /** Loaded */
            loaded: boolean;
            /** Ok */
            ok: boolean;
            /** Project Id */
            project_id?: number | null;
            /** Project Name */
            project_name?: string | null;
            /** Source */
            source: string;
        };
        /**
         * Island
         * @description A set of nodes that are one conductor, with one verdict for all of them.
         */
        Island: {
            /**
             * Bay Ids
             * @default []
             */
            bay_ids: string[];
            /**
             * Busbar Ids
             * @default []
             */
            busbar_ids: string[];
            /**
             * Earthed By
             * @default []
             */
            earthed_by: string[];
            /** Id */
            id: string;
            /**
             * Node Ids
             * @default []
             */
            node_ids: string[];
            reason: components["schemas"]["Reason"];
            /**
             * Seeds
             * @default []
             */
            seeds: string[];
            state: components["schemas"]["LiveState"];
            /**
             * Via
             * @default
             */
            via: string;
            /**
             * Voltage Level
             * @default
             */
            voltage_level: string;
        };
        /**
         * JunctionView
         * @description A real connection to a busbar. Drawn as a dot; a crossing has none.
         */
        JunctionView: {
            /** Id */
            id: string;
            /**
             * Node Id
             * @default
             */
            node_id: string;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * LinkOut
         * @description The state of the subscription itself.
         *
         *     `connected=False` does not mean the station is down — it means we have
         *     stopped hearing about it. What is on screen is then the last thing we knew,
         *     which is worth showing and worth labelling, but is not the present tense.
         */
        LinkOut: {
            /** Connected */
            connected: boolean;
            /** Error */
            error?: string | null;
            /** Realtime */
            realtime: boolean;
            /**
             * Rejected
             * @default 0
             */
            rejected: number;
            /** Since */
            since?: string | null;
            /**
             * Watching
             * @default 0
             */
            watching: number;
        };
        /**
         * LiveOut
         * @description Everything about the station that moves, in one document.
         *
         *     The split this expresses: `/api/diagram` is geometry and `/api/bays` is
         *     structure — both change only when the station is browsed again. Everything
         *     here changes constantly, and is exactly what `/api/stream` pushes. One
         *     shape for the first load and for every update, so the client has a single
         *     code path applying it.
         *
         *     `structure_revision` is the geometry's version. A client whose copy no
         *     longer matches must refetch the drawing before trusting these keys to join
         *     onto it.
         */
        LiveOut: {
            /**
             * Bay Is Live
             * @default {}
             */
            bay_is_live: {
                [key: string]: boolean | null;
            };
            /**
             * Devices
             * @default {}
             */
            devices: {
                [key: string]: components["schemas"]["DeviceLiveOut"];
            };
            energization?: components["schemas"]["EnergizationOut"] | null;
            link: components["schemas"]["LinkOut"];
            /** Loaded */
            loaded: boolean;
            /** Revision */
            revision: number;
            /** Structure Revision */
            structure_revision: number;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * LiveState
         * @description Energisation verdict for one island.
         *
         *     `UNKNOWN` is a first-class answer, not a failure: it is what an honest
         *     system says when the data cannot support `LIVE` or `DEAD`.
         * @enum {string}
         */
        LiveState: "LIVE" | "DEAD" | "EARTHED" | "UNKNOWN";
        /** Point */
        Point: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** ProjectCreateIn */
        ProjectCreateIn: {
            /** Name */
            name: string;
            /** Opcua Url */
            opcua_url: string;
        };
        /**
         * ProjectLoadOut
         * @description Result of creating/opening/refreshing a project.
         *
         *     `ok=False` means the project exists but its source could not be read —
         *     the row is kept so the operator can fix the URL or the network and retry.
         */
        ProjectLoadOut: {
            /** Error */
            error?: string | null;
            /** Ok */
            ok: boolean;
            project: components["schemas"]["ProjectOut"];
        };
        /** ProjectOut */
        ProjectOut: {
            /** Active */
            active: boolean;
            /** Captured At */
            captured_at: string | null;
            /** Created At */
            created_at: string;
            /** Has Snapshot */
            has_snapshot: boolean;
            /** Id */
            id: number;
            /** Model Name */
            model_name: string | null;
            /** Model Version */
            model_version: string | null;
            /** Name */
            name: string;
            /** Opcua Url */
            opcua_url: string;
            /** Snapshot Saved At */
            snapshot_saved_at: string | null;
            /** Updated At */
            updated_at: string;
        };
        /**
         * Quality
         * @description Quality of a measured point, collapsed from the OPC UA StatusCode.
         * @enum {string}
         */
        Quality: "GOOD" | "UNCERTAIN" | "BAD" | "MISSING";
        /** RailView */
        RailView: {
            /** Busbar Id */
            busbar_id: string;
            /**
             * Inferred
             * @default false
             */
            inferred: boolean;
            /** Is Live */
            is_live?: boolean | null;
            /** Label */
            label: string;
            /**
             * Node Id
             * @default
             */
            node_id: string;
            /** @default MISSING */
            quality: components["schemas"]["Quality"];
            /**
             * Transfer
             * @default false
             */
            transfer: boolean;
            /** X1 */
            x1: number;
            /** X2 */
            x2: number;
            /** Y */
            y: number;
        };
        /**
         * Reason
         * @description Why an island got its state.
         *
         *     A code, not a sentence. Operators read Vietnamese and the wording belongs to
         *     the UI; the API must not freeze it.
         * @enum {string}
         */
        Reason: "seeded_live" | "seeded_dead" | "through_transformer" | "possible_via_uncertain" | "earthed" | "no_measurement" | "isolated";
        /**
         * SectionView
         * @description One voltage level's band inside the station drawing.
         */
        SectionView: {
            /** Bay Count */
            bay_count: number;
            /** Bottom */
            bottom: number;
            /** Flipped */
            flipped: boolean;
            /** Top */
            top: number;
            /** Voltage Level */
            voltage_level: string;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "info" | "warning" | "error";
        /** StationOut */
        StationOut: {
            /** Bay Count */
            bay_count: number;
            /** Busbar Count */
            busbar_count: number;
            /** Captured At */
            captured_at: string | null;
            /** Coverage */
            coverage: {
                [key: string]: number;
            };
            /** Device Count */
            device_count: number;
            /** Issues */
            issues: components["schemas"]["ValidationIssue"][];
            /** Load Seconds */
            load_seconds: number | null;
            /** Model Version */
            model_version: string | null;
            /** Name */
            name: string;
            /** Node Count */
            node_count: number;
            /** Source */
            source: string;
            /** Voltage Levels */
            voltage_levels: string[];
        };
        /**
         * StationView
         * @description Every voltage level in one drawing, the way an SLD is normally read.
         */
        StationView: {
            /**
             * Columns
             * @default []
             */
            columns: components["schemas"]["ColumnView"][];
            /**
             * Edges
             * @default []
             */
            edges: components["schemas"]["EdgeView"][];
            /** Height */
            height: number;
            /**
             * Junctions
             * @default []
             */
            junctions: components["schemas"]["JunctionView"][];
            /** Name */
            name: string;
            /**
             * Rails
             * @default []
             */
            rails: components["schemas"]["RailView"][];
            /**
             * Sections
             * @default []
             */
            sections: components["schemas"]["SectionView"][];
            /**
             * Symbols
             * @default []
             */
            symbols: components["schemas"]["SymbolView"][];
            /**
             * Terminals
             * @default []
             */
            terminals: components["schemas"]["TerminalView"][];
            /**
             * Transformers
             * @default []
             */
            transformers: components["schemas"]["TransformerLinkView"][];
            /** Width */
            width: number;
        };
        /**
         * SwitchState
         * @description Position of a switching device.
         *
         *     Maps IEC 61850 Dbpos, but with one addition that matters (AGENTS.md I2):
         *     `UNDETERMINED` is what we report whenever quality is not GOOD. We never
         *     turn bad data into a position.
         * @enum {string}
         */
        SwitchState: "OPEN" | "CLOSED" | "INTERMEDIATE" | "UNDETERMINED";
        /** SymbolView */
        SymbolView: {
            /** Bay Id */
            bay_id: string;
            /** Device Id */
            device_id: string;
            /**
             * Flipped
             * @default false
             */
            flipped: boolean;
            /** Label */
            label: string;
            /** Ln */
            ln: string;
            quality: components["schemas"]["Quality"];
            role: components["schemas"]["DeviceRole"];
            state: components["schemas"]["SwitchState"];
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * TerminalView
         * @description Where the bay leaves the station: a line, a transformer, a feeder.
         */
        TerminalView: {
            /** Bay Type */
            bay_type: string;
            /**
             * Flipped
             * @default false
             */
            flipped: boolean;
            /** Label */
            label: string;
            /**
             * Linked
             * @default false
             */
            linked: boolean;
            /** Node Id */
            node_id: string;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * TransformerLinkView
         * @description A power transformer drawn between two voltage-level bands.
         *
         *     Only exists when the pairing is evidence-backed (see
         *     `domain.models.Transformer`); an unpaired transformer raises a
         *     ValidationIssue instead of a drawing.
         */
        TransformerLinkView: {
            /** Bay Ids */
            bay_ids: string[];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ValidationIssue
         * @description Something the builder could not resolve. Surfaced, never swallowed (I7).
         */
        ValidationIssue: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            severity: components["schemas"]["Severity"];
            /** Subject */
            subject?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    bays_api_bays_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BayOut"][];
                };
            };
        };
    };
    bay_detail_api_bays__bay_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BayDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    busbars_api_busbars_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusbarOut"][];
                };
            };
        };
    };
    station_diagram_api_diagram_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationView"];
                };
            };
        };
    };
    diagram_api_diagram__voltage_level__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voltage_level: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagramView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    energization_api_energization_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnergizationOut"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    live_api_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveOut"];
                };
            };
        };
    };
    projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectLoadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_project_api_projects__project_id__open_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectLoadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_project_api_projects__project_id__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectLoadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reload_station_api_reload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    station_api_station_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationOut"];
                };
            };
        };
    };
    stream_api_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Live state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
        };
    };
}
