/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask
         * @description Answer one question, whole.
         */
        post: operations["ask_api_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ask/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask Stream
         * @description The same answer, as it is produced (Server-Sent Events).
         *
         *     Frame types are `turn`, `tool`, `evidence`, `token` and `answer`; the last
         *     carries the complete `AnswerOut` and supersedes anything accumulated from
         *     `token`. See `agent/core.py` for why that replacement matters.
         */
        post: operations["ask_stream_api_ask_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bays */
        get: operations["bays_api_bays_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bays/{bay_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bay Detail */
        get: operations["bay_detail_api_bays__bay_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/busbars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busbars */
        get: operations["busbars_api_busbars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Station Diagram
         * @description The whole station in one drawing — every voltage level, stacked.
         */
        get: operations["station_diagram_api_diagram_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagram/{voltage_level}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diagram */
        get: operations["diagram_api_diagram__voltage_level__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/energization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Energization
         * @description Solve which sections are live from the switch positions we can read.
         *
         *     Seeded from the busbars the station measures, spread across closed devices
         *     and through paired transformers, then compared against the bay-level
         *     `IsLive` OneATS publishes. Disagreements are returned, not hidden (I7).
         */
        get: operations["energization_api_energization_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Issues */
        get: operations["list_issues_api_issues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live
         * @description One poll of everything `/api/stream` pushes. The fallback when SSE cannot
         *     get through, and what the UI loads before the stream's first event.
         */
        get: operations["live_api_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Verify a password and start a session.
         *
         *     Writes a row to the local SQLite store and sets a cookie. Nothing here
         *     reaches OneATS (I1) — this endpoint is about who is looking at the station,
         *     not about the station.
         */
        post: operations["login_api_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description End the session server-side and clear the cookie.
         */
        post: operations["logout_api_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description The current caller, or an empty identity when nobody is signed in.
         *
         *     Resolved through `get_principal`, not by reading the cookie here: every
         *     facet must agree about who is calling, and a second way of working that out
         *     is a second answer waiting to disagree with the first.
         */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Change your own password. The current one has to be given again.
         *
         *     Only your own: changing somebody else's belongs with `account.manage` and
         *     an audit record, and that screen does not exist yet. Better absent than
         *     half-built.
         */
        post: operations["change_password_api_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projects */
        get: operations["projects_api_projects_get"];
        put?: never;
        /**
         * Create Project
         * @description Create a project and immediately try to browse its DataServer.
         *
         *     Success stores a snapshot and makes the project active. Failure keeps the
         *     project so the URL can be corrected and retried with /refresh.
         */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Project
         * @description Remove a project and its snapshot. Returns the remaining projects.
         */
        delete: operations["delete_project_api_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open Project
         * @description Make this project current. Renders from its snapshot when one exists;
         *     only its first-ever open touches the DataServer.
         */
        post: operations["open_project_api_projects__project_id__open_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Project
         * @description Browse the project's DataServer live and replace its snapshot.
         */
        post: operations["refresh_project_api_projects__project_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reload Station
         * @description Re-read the current source: the active project's DataServer (updating
         *     its snapshot), else BI_SOURCE. Writes nothing to OneATS (I1).
         */
        post: operations["reload_station_api_reload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/station": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Station */
        get: operations["station_api_station_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream
         * @description Push each cadence whenever it moves (Server-Sent Events).
         *
         *     The first three events are the current state, measurements and link, so a
         *     client needs no separate initial fetch. Read-only in both directions: SSE
         *     has no channel back, and the data behind it is a subscription to OneATS,
         *     never a command to it (I1).
         */
        get: operations["stream_api_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Summary
         * @description How this part of the station is doing, with the evidence behind it.
         */
        get: operations["summary_api_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnswerOut
         * @description One turn of conversation, with everything behind it.
         *
         *     The same object arrives two ways: whole from `POST /api/ask`, and in pieces
         *     from `POST /api/ask/stream`. Same schema either way, so a client applies an
         *     answer with one code path whichever it used — the reasoning behind
         *     `/api/live` and `/api/stream` (ADR-0012), for the same reason.
         *
         *     Prose and facts are separate fields on purpose (I3). `text` is what a
         *     language model wrote and is labelled as interpretation; `summary`,
         *     `resolution` and `evidence` are computed and are what the interface may
         *     show as fact. When `generated` is false there is no model in the loop at
         *     all and `key`/`params` carry a computed statement for the frontend to
         *     render in its own language.
         */
        AnswerOut: {
            /** Conversation Id */
            conversation_id: string;
            /**
             * Evidence
             * @default []
             */
            evidence: components["schemas"]["EvidenceRecord"][];
            /** Generated */
            generated: boolean;
            /** Key */
            key?: string | null;
            /** Llm Error */
            llm_error?: string | null;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: string | number | boolean | null;
            };
            /** Provider */
            provider: string;
            /** Question */
            question: string;
            resolution?: components["schemas"]["ResolveOut"] | null;
            /** Scope */
            scope: string;
            summary?: components["schemas"]["SummaryOut"] | null;
            /**
             * Text
             * @default
             */
            text: string;
            /** Turn Id */
            turn_id: string;
        };
        /**
         * AskIn
         * @description A question, and where the person asking was looking when they asked it.
         *
         *     `scope` is the fallback subject, used when the question names nothing —
         *     "còn số đo thì sao?" means *this* bay, and the pane knows which one.
         *     `conversation_id` continues an existing thread; omit it to start one.
         */
        AskIn: {
            /** Conversation Id */
            conversation_id?: string | null;
            /** Question */
            question: string;
            /**
             * Scope
             * @default station
             */
            scope: string;
        };
        /** BayDetailOut */
        BayDetailOut: {
            /** Bay Type */
            bay_type: string;
            /** Device Count */
            device_count: number;
            /** Devices */
            devices: components["schemas"]["DeviceOut"][];
            /** Id */
            id: string;
            /** Is Live */
            is_live: boolean | null;
            is_live_quality: components["schemas"]["Quality"];
            /** Issues */
            issues: components["schemas"]["ValidationIssueOut"][];
            /** Logical Nodes */
            logical_nodes: string[];
            /** Name */
            name: string;
            /** Template Id */
            template_id: string | null;
            /** Voltage Level */
            voltage_level: string;
        };
        /** BayOut */
        BayOut: {
            /** Bay Type */
            bay_type: string;
            /** Device Count */
            device_count: number;
            /** Id */
            id: string;
            /** Is Live */
            is_live: boolean | null;
            is_live_quality: components["schemas"]["Quality"];
            /** Issues */
            issues: components["schemas"]["ValidationIssueOut"][];
            /** Logical Nodes */
            logical_nodes: string[];
            /** Name */
            name: string;
            /** Template Id */
            template_id: string | null;
            /** Voltage Level */
            voltage_level: string;
        };
        /** BusbarOut */
        BusbarOut: {
            /** Id */
            id: string;
            /** Index */
            index: number;
            /** Inferred */
            inferred: boolean;
            /** Is Live */
            is_live: boolean | null;
            /** Name */
            name: string;
            quality: components["schemas"]["Quality"];
            /** Voltage Level */
            voltage_level: string;
        };
        /** ColumnView */
        ColumnView: {
            /** Bay Id */
            bay_id: string;
            /** Bay Type */
            bay_type: string;
            /** Bottom */
            bottom: number;
            /** Caption */
            caption: string;
            /**
             * Error Count
             * @default 0
             */
            error_count: number;
            /**
             * Flipped
             * @default false
             */
            flipped: boolean;
            /**
             * Issue Count
             * @default 0
             */
            issue_count: number;
            /** Label */
            label: string;
            /** Label Y */
            label_y: number;
            /** Template Id */
            template_id: string | null;
            /** Top */
            top: number;
            /** X */
            x: number;
        };
        /**
         * Coverage
         * @description How much of what was asked for could actually be answered.
         *
         *     `resolved < requested` is the natural home for drift (I7): a NodeId that
         *     stopped resolving shows up here rather than as a silently shorter list.
         */
        Coverage: {
            /**
             * Missing
             * @default []
             */
            missing: string[];
            /**
             * Requested
             * @default 0
             */
            requested: number;
            /**
             * Resolved
             * @default 0
             */
            resolved: number;
        };
        /**
         * CrossCheck
         * @description Our verdict for a bay against the one OneATS publishes for it.
         *
         *     `agrees is None` means the comparison could not be made — either we say
         *     `UNKNOWN` or OneATS's `IsLive` is not readable. Not comparable is not the
         *     same as agreeing, and is never counted as one.
         */
        CrossCheck: {
            /** Agrees */
            agrees?: boolean | null;
            /** Bay Id */
            bay_id: string;
            computed: components["schemas"]["LiveState"];
            /** Node Id */
            node_id: string;
            /** @default MISSING */
            quality: components["schemas"]["Quality"];
            /** Reported */
            reported?: boolean | null;
        };
        /**
         * DeviceLiveOut
         * @description A switching device's position, and how much to trust it.
         *
         *     `value` is the raw Dbpos behind `state`, carried so a panel showing live
         *     data can still show its provenance — an operator questioning a symbol
         *     should not have to refetch the bay to see what the DataServer actually
         *     said (I6).
         */
        DeviceLiveOut: {
            quality: components["schemas"]["Quality"];
            /** Source Timestamp */
            source_timestamp?: string | null;
            state: components["schemas"]["SwitchState"];
            /** Value */
            value?: number | boolean | string | null;
        };
        /** DeviceOut */
        DeviceOut: {
            /** Id */
            id: string;
            /** Ln */
            ln: string;
            /** Name */
            name: string;
            quality: components["schemas"]["Quality"];
            /** Role */
            role: string;
            /** Short Name */
            short_name: string;
            /** Source Ref */
            source_ref: string | null;
            /** Source Timestamp */
            source_timestamp: string | null;
            state: components["schemas"]["SwitchState"];
            /** Terminals */
            terminals: string[];
            /** Value */
            value: number | boolean | string | null;
        };
        /**
         * DeviceRole
         * @description Electrical role of a switching device inside its bay.
         * @enum {string}
         */
        DeviceRole: "breaker" | "busbar_selector" | "transfer_selector" | "line_disconnector" | "transformer_disconnector" | "earth_switch";
        /** DiagramView */
        DiagramView: {
            /**
             * Columns
             * @default []
             */
            columns: components["schemas"]["ColumnView"][];
            /**
             * Edges
             * @default []
             */
            edges: components["schemas"]["EdgeView"][];
            /** Height */
            height: number;
            /**
             * Junctions
             * @default []
             */
            junctions: components["schemas"]["JunctionView"][];
            /**
             * Rails
             * @default []
             */
            rails: components["schemas"]["RailView"][];
            /**
             * Symbols
             * @default []
             */
            symbols: components["schemas"]["SymbolView"][];
            /**
             * Terminals
             * @default []
             */
            terminals: components["schemas"]["TerminalView"][];
            /** Voltage Level */
            voltage_level: string;
            /** Width */
            width: number;
        };
        /** EdgeView */
        EdgeView: {
            /** Device Id */
            device_id?: string | null;
            /** Id */
            id: string;
            /** Node Id */
            node_id?: string | null;
            /** Points */
            points: components["schemas"]["Point"][];
        };
        /**
         * EnergizationOut
         * @description Which conductors are live, why, and whether OneATS agrees.
         *
         *     `node_state` is keyed by connectivity node so the drawing can be coloured by
         *     joining on `RailView.node_id` / `EdgeView.node_id` — geometry and
         *     energisation stay separate, which is what will let the realtime module push
         *     a new verdict without re-laying-out the station.
         */
        EnergizationOut: {
            /** Checks */
            checks: components["schemas"]["CrossCheck"][];
            /** Islands */
            islands: components["schemas"]["Island"][];
            /** Issues */
            issues: components["schemas"]["ValidationIssueOut"][];
            /** Node State */
            node_state: {
                [key: string]: components["schemas"]["LiveState"];
            };
            /** Summary */
            summary: {
                [key: string]: number;
            };
        };
        /**
         * EvidenceRecord
         * @description What a facet knew, when, from where, and how well.
         *
         *     `subject` is a scope ref (ADR-0010), so evidence, URL, pane and tool argument
         *     are the same vocabulary rather than four dialects of it.
         */
        EvidenceRecord: {
            /** Actor */
            actor?: string | null;
            /** Args */
            args?: {
                [key: string]: string | number | boolean | null;
            };
            /**
             * Called At
             * Format: date-time
             */
            called_at: string;
            /**
             * @default {
             *       "missing": [],
             *       "requested": 0,
             *       "resolved": 0
             *     }
             */
            coverage: components["schemas"]["Coverage"];
            /**
             * Limits
             * @default []
             */
            limits: components["schemas"]["Limit"][];
            /** Model Version */
            model_version?: string | null;
            /**
             * Quality
             * @default []
             */
            quality: components["schemas"]["PointQ"][];
            /** Release */
            release?: string | null;
            source: components["schemas"]["Source"];
            /** Subject */
            subject: string;
            /** Tool */
            tool: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Load Error */
            load_error?: string | null;
            /** Load Seconds */
            load_seconds?: number | null;
            /** Loaded */
            loaded: boolean;
            /** Ok */
            ok: boolean;
            /** Project Id */
            project_id?: number | null;
            /** Project Name */
            project_name?: string | null;
            /** Source */
            source: string;
        };
        /**
         * Island
         * @description A set of nodes that are one conductor, with one verdict for all of them.
         */
        Island: {
            /**
             * Bay Ids
             * @default []
             */
            bay_ids: string[];
            /**
             * Busbar Ids
             * @default []
             */
            busbar_ids: string[];
            /**
             * Earthed By
             * @default []
             */
            earthed_by: string[];
            /** Id */
            id: string;
            /**
             * Node Ids
             * @default []
             */
            node_ids: string[];
            reason: components["schemas"]["Reason"];
            /**
             * Seeds
             * @default []
             */
            seeds: string[];
            state: components["schemas"]["LiveState"];
            /**
             * Via
             * @default
             */
            via: string;
            /**
             * Voltage Level
             * @default
             */
            voltage_level: string;
        };
        /** IssuesOut */
        IssuesOut: {
            /** Issues */
            issues: components["schemas"]["ValidationIssueOut"][];
        };
        /**
         * JunctionView
         * @description A real connection to a busbar. Drawn as a dot; a crossing has none.
         */
        JunctionView: {
            /** Id */
            id: string;
            /**
             * Node Id
             * @default
             */
            node_id: string;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * Limit
         * @description One caveat, machine-readable so the UI can rank and translate it.
         */
        Limit: {
            code: components["schemas"]["LimitCode"];
            /**
             * Count
             * @default 0
             */
            count: number;
            /**
             * Subjects
             * @default []
             */
            subjects: string[];
        };
        /**
         * LimitCode
         * @description Why an answer is worth less than it looks.
         * @enum {string}
         */
        LimitCode: "points_missing" | "quality_not_good" | "data_stale" | "from_snapshot" | "link_down" | "deadband_applied" | "no_history" | "unit_unverified";
        /**
         * LinkOut
         * @description The state of the subscription itself.
         *
         *     `connected=False` does not mean the station is down — it means we have
         *     stopped hearing about it. What is on screen is then the last thing we knew,
         *     which is worth showing and worth labelling, but is not the present tense.
         */
        LinkOut: {
            /** Connected */
            connected: boolean;
            /** Error */
            error?: string | null;
            /** Realtime */
            realtime: boolean;
            /**
             * Rejected
             * @default 0
             */
            rejected: number;
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /** Since */
            since?: string | null;
            /**
             * Watching
             * @default 0
             */
            watching: number;
        };
        /**
         * LiveOut
         * @description Everything that moves, in one document — the shape `/api/live` returns.
         *
         *     The stream sends these three as separate typed events at their own rates
         *     (ADR-0012); the poll endpoint hands over all three at once, because a
         *     client that has just connected needs the whole present tense before it can
         *     render anything. Same schemas either way, so there is still one code path
         *     applying each cadence.
         */
        LiveOut: {
            link: components["schemas"]["LinkOut"];
            measurement: components["schemas"]["MeasurementOut"];
            state: components["schemas"]["StateOut"];
        };
        /**
         * LiveState
         * @description Energisation verdict for one island.
         *
         *     `UNKNOWN` is a first-class answer, not a failure: it is what an honest
         *     system says when the data cannot support `LIVE` or `DEAD`.
         * @enum {string}
         */
        LiveState: "LIVE" | "DEAD" | "EARTHED" | "UNKNOWN";
        /** LoginIn */
        LoginIn: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /**
         * MeOut
         * @description The caller's identity and permissions (ADR-0016, ADR-0017).
         *
         *     `capabilities` is the field the UI switches on. `roles` is for display and
         *     for support calls — "which roles is this account holding" is the first
         *     question when somebody reports a missing button.
         *
         *     `authenticated=False` means nobody is signed in, which is not an error: it
         *     is what `/api/me` answers before the login screen has been used.
         */
        MeOut: {
            /**
             * Auth Mode
             * @default session
             */
            auth_mode: string;
            /**
             * Authenticated
             * @default false
             */
            authenticated: boolean;
            /** Capabilities */
            capabilities: string[];
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /** Roles */
            roles: string[];
            /** User */
            user: string;
        };
        /**
         * MeasurementOut
         * @description What the station is *reading*. The `measurement` cadence.
         *
         *     Keyed by subject so a panel scoped to `bay:D03` looks up exactly its own
         *     readings. Subjects with no instrument transformers are simply absent —
         *     an empty list would claim we looked and found nothing.
         */
        MeasurementOut: {
            /** Deadband Override Pct */
            deadband_override_pct?: number | null;
            /** Measured At */
            measured_at?: string | null;
            /**
             * Readings
             * @default {}
             */
            readings: {
                [key: string]: components["schemas"]["ReadingOut"][];
            };
            /** Revision */
            revision: number;
        };
        /** PasswordChangeIn */
        PasswordChangeIn: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** Point */
        Point: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * PointQ
         * @description One point as it was read, with everything needed to judge it (I2).
         */
        PointQ: {
            /** Age Ms */
            age_ms?: number | null;
            /** Point */
            point: string;
            /** @default MISSING */
            quality: components["schemas"]["Quality"];
            /** Ts Source */
            ts_source?: string | null;
            /** Value */
            value?: number | boolean | string | null;
        };
        /** ProjectCreateIn */
        ProjectCreateIn: {
            /** Name */
            name: string;
            /** Opcua Url */
            opcua_url: string;
        };
        /**
         * ProjectLoadOut
         * @description Result of creating/opening/refreshing a project.
         *
         *     `ok=False` means the project exists but its source could not be read —
         *     the row is kept so the operator can fix the URL or the network and retry.
         */
        ProjectLoadOut: {
            /** Error */
            error?: string | null;
            /** Ok */
            ok: boolean;
            project: components["schemas"]["ProjectOut"];
        };
        /** ProjectOut */
        ProjectOut: {
            /** Active */
            active: boolean;
            /** Captured At */
            captured_at: string | null;
            /** Created At */
            created_at: string;
            /** Has Snapshot */
            has_snapshot: boolean;
            /** Id */
            id: number;
            /** Model Name */
            model_name: string | null;
            /** Model Version */
            model_version: string | null;
            /** Name */
            name: string;
            /** Opcua Url */
            opcua_url: string;
            /** Snapshot Saved At */
            snapshot_saved_at: string | null;
            /** Updated At */
            updated_at: string;
        };
        /**
         * Quality
         * @description Quality of a measured point, collapsed from the OPC UA StatusCode.
         * @enum {string}
         */
        Quality: "GOOD" | "UNCERTAIN" | "BAD" | "MISSING";
        /**
         * Quantity
         * @description What is being measured. Always known; unlike the unit, never in doubt.
         * @enum {string}
         */
        Quantity: "active_power" | "reactive_power" | "power_factor" | "voltage" | "current" | "frequency" | "tap_position";
        /** RailView */
        RailView: {
            /** Busbar Id */
            busbar_id: string;
            /**
             * Inferred
             * @default false
             */
            inferred: boolean;
            /** Is Live */
            is_live?: boolean | null;
            /** Label */
            label: string;
            /**
             * Node Id
             * @default
             */
            node_id: string;
            /** @default MISSING */
            quality: components["schemas"]["Quality"];
            /**
             * Transfer
             * @default false
             */
            transfer: boolean;
            /** X1 */
            x1: number;
            /** X2 */
            x2: number;
            /** Y */
            y: number;
        };
        /**
         * ReadingOut
         * @description One analog value, with everything needed to distrust it.
         *
         *     `unit` is `"?"` when the scale was never measured — see the module
         *     docstring of `domain/measurement.py`. A client must then print the quantity
         *     name instead of inventing a unit.
         *
         *     `value` is null unless quality is GOOD. The raw number is still on
         *     `raw_value` for provenance, so a panel can show what the DataServer said
         *     without implying the number is usable (I2, I6).
         */
        ReadingOut: {
            /**
             * Deadband Abs
             * @default 0
             */
            deadband_abs: number;
            /**
             * Deadband Pct
             * @default 0
             */
            deadband_pct: number;
            /** Id */
            id: string;
            /** Measurand */
            measurand: string;
            quality: components["schemas"]["Quality"];
            quantity: components["schemas"]["Quantity"];
            /** Raw Value */
            raw_value?: number | boolean | string | null;
            /** Source Ref */
            source_ref?: string | null;
            /** Source Timestamp */
            source_timestamp?: string | null;
            /** Subject */
            subject: string;
            unit: components["schemas"]["Unit"];
            /** Value */
            value?: number | null;
        };
        /**
         * Reason
         * @description Why an island got its state.
         *
         *     A code, not a sentence. Operators read Vietnamese and the wording belongs to
         *     the UI; the API must not freeze it.
         * @enum {string}
         */
        Reason: "seeded_live" | "seeded_dead" | "through_transformer" | "possible_via_uncertain" | "earthed" | "no_measurement" | "isolated";
        /**
         * ResolveOut
         * @description What a name refers to — the deterministic half of every question (I8).
         *
         *     `scope` is non-null only when exactly one thing matched. Several matches is
         *     a normal answer, not an error: "Lai Uyen" is the name of two bays on
         *     DEMO_SAS, and the right response is to ask which, never to pick one.
         */
        ResolveOut: {
            /**
             * Ambiguous
             * @default false
             */
            ambiguous: boolean;
            /**
             * Candidates
             * @default []
             */
            candidates: components["schemas"]["ScopeCandidateOut"][];
            /**
             * Label
             * @default
             */
            label: string;
            /** Query */
            query: string;
            /** Scope */
            scope?: string | null;
        };
        /**
         * ScopeCandidateOut
         * @description One thing a piece of text could have named.
         */
        ScopeCandidateOut: {
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Matched */
            matched: string;
            /** Scope */
            scope: string;
            /** Tier */
            tier: string;
        };
        /**
         * SectionView
         * @description One voltage level's band inside the station drawing.
         */
        SectionView: {
            /** Bay Count */
            bay_count: number;
            /** Bottom */
            bottom: number;
            /** Flipped */
            flipped: boolean;
            /** Top */
            top: number;
            /** Voltage Level */
            voltage_level: string;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "info" | "warning" | "error";
        /**
         * Source
         * @description The provenance of an answer, down to the release it was pinned to.
         */
        Source: {
            /** Catalog Snapshot */
            catalog_snapshot?: string | null;
            /** Endpoint */
            endpoint?: string | null;
            kind: components["schemas"]["SourceKind"];
            /**
             * Node Ids
             * @default []
             */
            node_ids: string[];
        };
        /**
         * SourceKind
         * @description Where the numbers in this answer physically came from.
         * @enum {string}
         */
        SourceKind: "opcua" | "snapshot" | "fixture" | "store" | "derived";
        /**
         * StateOut
         * @description What the station *is*: positions, `IsLive`, and the solved energisation.
         *
         *     The `state` cadence of the stream (ADR-0012). Every field here is discrete
         *     and safety-relevant, so nothing on this path is throttled or deadbanded.
         *
         *     `structure_revision` is the geometry's version. A client whose copy no
         *     longer matches must refetch the drawing before trusting these keys to join
         *     onto it.
         */
        StateOut: {
            /**
             * Bay Is Live
             * @default {}
             */
            bay_is_live: {
                [key: string]: boolean | null;
            };
            /**
             * Devices
             * @default {}
             */
            devices: {
                [key: string]: components["schemas"]["DeviceLiveOut"];
            };
            energization?: components["schemas"]["EnergizationOut"] | null;
            /** Loaded */
            loaded: boolean;
            /** Revision */
            revision: number;
            /** Structure Revision */
            structure_revision: number;
            /** Updated At */
            updated_at?: string | null;
        };
        /** StationOut */
        StationOut: {
            /** Bay Count */
            bay_count: number;
            /** Busbar Count */
            busbar_count: number;
            /** Captured At */
            captured_at: string | null;
            /** Coverage */
            coverage: {
                [key: string]: number;
            };
            /** Device Count */
            device_count: number;
            /** Issues */
            issues: components["schemas"]["ValidationIssueOut"][];
            /** Load Seconds */
            load_seconds: number | null;
            /** Model Version */
            model_version: string | null;
            /** Name */
            name: string;
            /** Node Count */
            node_count: number;
            /** Source */
            source: string;
            /** Voltage Levels */
            voltage_levels: string[];
        };
        /**
         * StationView
         * @description Every voltage level in one drawing, the way an SLD is normally read.
         */
        StationView: {
            /**
             * Columns
             * @default []
             */
            columns: components["schemas"]["ColumnView"][];
            /**
             * Edges
             * @default []
             */
            edges: components["schemas"]["EdgeView"][];
            /** Height */
            height: number;
            /**
             * Junctions
             * @default []
             */
            junctions: components["schemas"]["JunctionView"][];
            /** Name */
            name: string;
            /**
             * Rails
             * @default []
             */
            rails: components["schemas"]["RailView"][];
            /**
             * Sections
             * @default []
             */
            sections: components["schemas"]["SectionView"][];
            /**
             * Symbols
             * @default []
             */
            symbols: components["schemas"]["SymbolView"][];
            /**
             * Terminals
             * @default []
             */
            terminals: components["schemas"]["TerminalView"][];
            /**
             * Transformers
             * @default []
             */
            transformers: components["schemas"]["TransformerLinkView"][];
            /** Width */
            width: number;
        };
        /**
         * SummaryOut
         * @description How one scope is doing right now — the first evidence-bearing facet.
         *
         *     Answers the question Module A exists for ("what is the state of D03?") in
         *     one call, and attaches the `EvidenceRecord` that says how far that answer
         *     can be trusted: which points were asked for, which came back, how old they
         *     are, and what is degraded about them (ADR-0013).
         *
         *     The evidence is built by this endpoint, never by a language model (I3).
         */
        SummaryOut: {
            /** Bays */
            bays: string[];
            evidence: components["schemas"]["EvidenceRecord"];
            /** Issues */
            issues: components["schemas"]["ValidationIssueOut"][];
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Measurements */
            measurements: components["schemas"]["ReadingOut"][];
            /** Node States */
            node_states: {
                [key: string]: number;
            };
            /** Scope */
            scope: string;
            /** Switch States */
            switch_states: {
                [key: string]: number;
            };
        };
        /**
         * SwitchState
         * @description Position of a switching device.
         *
         *     Maps IEC 61850 Dbpos, but with one addition that matters (AGENTS.md I2):
         *     `UNDETERMINED` is what we report whenever quality is not GOOD. We never
         *     turn bad data into a position.
         * @enum {string}
         */
        SwitchState: "OPEN" | "CLOSED" | "INTERMEDIATE" | "UNDETERMINED";
        /** SymbolView */
        SymbolView: {
            /** Bay Id */
            bay_id: string;
            /** Device Id */
            device_id: string;
            /**
             * Flipped
             * @default false
             */
            flipped: boolean;
            /** Label */
            label: string;
            /** Ln */
            ln: string;
            quality: components["schemas"]["Quality"];
            role: components["schemas"]["DeviceRole"];
            state: components["schemas"]["SwitchState"];
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * TerminalView
         * @description Where the bay leaves the station: a line, a transformer, a feeder.
         */
        TerminalView: {
            /** Bay Type */
            bay_type: string;
            /**
             * Flipped
             * @default false
             */
            flipped: boolean;
            /** Label */
            label: string;
            /**
             * Linked
             * @default false
             */
            linked: boolean;
            /** Node Id */
            node_id: string;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * TransformerLinkView
         * @description A power transformer drawn between two voltage-level bands.
         *
         *     Only exists when the pairing is evidence-backed (see
         *     `domain.models.Transformer`); an unpaired transformer raises a
         *     ValidationIssue instead of a drawing.
         */
        TransformerLinkView: {
            /** Bay Ids */
            bay_ids: string[];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * Unit
         * @description The unit to print after the number, when we are entitled to print one.
         *
         *     `UNKNOWN` is a deliberate sentinel rather than an empty string: it must be
         *     impossible to confuse "we did not measure the scale" with "this quantity is
         *     dimensionless". Power factor is the second case and gets `NONE`.
         * @enum {string}
         */
        Unit: "?" | "" | "Hz" | "step";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ValidationIssueOut
         * @description A builder issue on the wire, with its UI group (A/B/C).
         */
        ValidationIssueOut: {
            /** Code */
            code: string;
            /**
             * Group
             * @enum {string}
             */
            group: "A" | "B" | "C";
            /** Message */
            message: string;
            severity: components["schemas"]["Severity"];
            /** Subject */
            subject?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ask_api_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_stream_api_ask_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskIn"];
            };
        };
        responses: {
            /** @description Answer frames */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bays_api_bays_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BayOut"][];
                };
            };
        };
    };
    bay_detail_api_bays__bay_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BayDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    busbars_api_busbars_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusbarOut"][];
                };
            };
        };
    };
    station_diagram_api_diagram_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationView"];
                };
            };
        };
    };
    diagram_api_diagram__voltage_level__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voltage_level: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagramView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    energization_api_energization_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnergizationOut"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    list_issues_api_issues_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuesOut"];
                };
            };
        };
    };
    live_api_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveOut"];
                };
            };
        };
    };
    login_api_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    change_password_api_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectLoadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_project_api_projects__project_id__open_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectLoadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_project_api_projects__project_id__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectLoadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reload_station_api_reload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    station_api_station_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationOut"];
                };
            };
        };
    };
    stream_api_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Live cadences */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
        };
    };
    summary_api_summary_get: {
        parameters: {
            query?: {
                /** @description Scope ref, e.g. station, vl:220kV, bay:D03 */
                scope?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
