/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/bays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bays */
        get: operations["bays_api_bays_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bays/{bay_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bay Detail */
        get: operations["bay_detail_api_bays__bay_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/busbars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busbars */
        get: operations["busbars_api_busbars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagram/{voltage_level}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diagram */
        get: operations["diagram_api_diagram__voltage_level__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reload Station
         * @description Re-read the source. The only non-GET endpoint, and it writes nothing
         *     to OneATS.
         */
        post: operations["reload_station_api_reload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/station": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Station */
        get: operations["station_api_station_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BayDetailOut */
        BayDetailOut: {
            /** Bay Type */
            bay_type: string;
            /** Device Count */
            device_count: number;
            /** Devices */
            devices: components["schemas"]["DeviceOut"][];
            /** Id */
            id: string;
            /** Is Live */
            is_live: boolean | null;
            is_live_quality: components["schemas"]["Quality"];
            /** Issues */
            issues: components["schemas"]["ValidationIssue"][];
            /** Logical Nodes */
            logical_nodes: string[];
            /** Name */
            name: string;
            /** Template Id */
            template_id: string | null;
            /** Voltage Level */
            voltage_level: string;
        };
        /** BayOut */
        BayOut: {
            /** Bay Type */
            bay_type: string;
            /** Device Count */
            device_count: number;
            /** Id */
            id: string;
            /** Is Live */
            is_live: boolean | null;
            is_live_quality: components["schemas"]["Quality"];
            /** Issues */
            issues: components["schemas"]["ValidationIssue"][];
            /** Logical Nodes */
            logical_nodes: string[];
            /** Name */
            name: string;
            /** Template Id */
            template_id: string | null;
            /** Voltage Level */
            voltage_level: string;
        };
        /** BusbarOut */
        BusbarOut: {
            /** Id */
            id: string;
            /** Index */
            index: number;
            /** Inferred */
            inferred: boolean;
            /** Is Live */
            is_live: boolean | null;
            /** Name */
            name: string;
            quality: components["schemas"]["Quality"];
            /** Voltage Level */
            voltage_level: string;
        };
        /** ColumnView */
        ColumnView: {
            /** Bay Id */
            bay_id: string;
            /** Bay Type */
            bay_type: string;
            /** Bottom */
            bottom: number;
            /**
             * Error Count
             * @default 0
             */
            error_count: number;
            /**
             * Issue Count
             * @default 0
             */
            issue_count: number;
            /** Label */
            label: string;
            /** Template Id */
            template_id: string | null;
            /** Top */
            top: number;
            /** X */
            x: number;
        };
        /** DeviceOut */
        DeviceOut: {
            /** Id */
            id: string;
            /** Ln */
            ln: string;
            /** Name */
            name: string;
            quality: components["schemas"]["Quality"];
            /** Role */
            role: string;
            /** Short Name */
            short_name: string;
            /** Source Ref */
            source_ref: string | null;
            /** Source Timestamp */
            source_timestamp: string | null;
            state: components["schemas"]["SwitchState"];
            /** Terminals */
            terminals: string[];
            /** Value */
            value: number | boolean | string | null;
        };
        /**
         * DeviceRole
         * @description Electrical role of a switching device inside its bay.
         * @enum {string}
         */
        DeviceRole: "breaker" | "busbar_selector" | "transfer_selector" | "line_disconnector" | "transformer_disconnector" | "earth_switch";
        /** DiagramView */
        DiagramView: {
            /**
             * Columns
             * @default []
             */
            columns: components["schemas"]["ColumnView"][];
            /**
             * Edges
             * @default []
             */
            edges: components["schemas"]["EdgeView"][];
            /** Height */
            height: number;
            /**
             * Rails
             * @default []
             */
            rails: components["schemas"]["RailView"][];
            /**
             * Symbols
             * @default []
             */
            symbols: components["schemas"]["SymbolView"][];
            /**
             * Terminals
             * @default []
             */
            terminals: components["schemas"]["TerminalView"][];
            /** Voltage Level */
            voltage_level: string;
            /** Width */
            width: number;
        };
        /** EdgeView */
        EdgeView: {
            /** Device Id */
            device_id?: string | null;
            /** Id */
            id: string;
            /** Points */
            points: components["schemas"]["Point"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Load Error */
            load_error?: string | null;
            /** Load Seconds */
            load_seconds?: number | null;
            /** Loaded */
            loaded: boolean;
            /** Ok */
            ok: boolean;
            /** Source */
            source: string;
        };
        /** Point */
        Point: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * Quality
         * @description Quality of a measured point, collapsed from the OPC UA StatusCode.
         * @enum {string}
         */
        Quality: "GOOD" | "UNCERTAIN" | "BAD" | "MISSING";
        /** RailView */
        RailView: {
            /** Busbar Id */
            busbar_id: string;
            /**
             * Inferred
             * @default false
             */
            inferred: boolean;
            /** Is Live */
            is_live?: boolean | null;
            /** Label */
            label: string;
            /** @default MISSING */
            quality: components["schemas"]["Quality"];
            /** X1 */
            x1: number;
            /** X2 */
            x2: number;
            /** Y */
            y: number;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "info" | "warning" | "error";
        /** StationOut */
        StationOut: {
            /** Bay Count */
            bay_count: number;
            /** Busbar Count */
            busbar_count: number;
            /** Captured At */
            captured_at: string | null;
            /** Coverage */
            coverage: {
                [key: string]: number;
            };
            /** Device Count */
            device_count: number;
            /** Issues */
            issues: components["schemas"]["ValidationIssue"][];
            /** Load Seconds */
            load_seconds: number | null;
            /** Model Version */
            model_version: string | null;
            /** Name */
            name: string;
            /** Node Count */
            node_count: number;
            /** Source */
            source: string;
            /** Voltage Levels */
            voltage_levels: string[];
        };
        /**
         * SwitchState
         * @description Position of a switching device.
         *
         *     Maps IEC 61850 Dbpos, but with one addition that matters (AGENTS.md I2):
         *     `UNDETERMINED` is what we report whenever quality is not GOOD. We never
         *     turn bad data into a position.
         * @enum {string}
         */
        SwitchState: "OPEN" | "CLOSED" | "INTERMEDIATE" | "UNDETERMINED";
        /** SymbolView */
        SymbolView: {
            /** Bay Id */
            bay_id: string;
            /** Device Id */
            device_id: string;
            /** Label */
            label: string;
            /** Ln */
            ln: string;
            quality: components["schemas"]["Quality"];
            role: components["schemas"]["DeviceRole"];
            state: components["schemas"]["SwitchState"];
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * TerminalView
         * @description Where the bay leaves the station: a line, a transformer, a feeder.
         */
        TerminalView: {
            /** Label */
            label: string;
            /** Node Id */
            node_id: string;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ValidationIssue
         * @description Something the builder could not resolve. Surfaced, never swallowed (I7).
         */
        ValidationIssue: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            severity: components["schemas"]["Severity"];
            /** Subject */
            subject?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    bays_api_bays_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BayOut"][];
                };
            };
        };
    };
    bay_detail_api_bays__bay_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BayDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    busbars_api_busbars_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusbarOut"][];
                };
            };
        };
    };
    diagram_api_diagram__voltage_level__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voltage_level: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagramView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    reload_station_api_reload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    station_api_station_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationOut"];
                };
            };
        };
    };
}
